
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # Use Install phase to install packages or any pre-reqs you may need throughout the build (e.g. dev deps, security checks, etc.)
      # - echo "[Install phase]"
  pre_build:
    commands:
      # Use Pre-Build phase to run tests, install any code deps or any other customization before build
      # - echo "[Pre-Build phase]"
  build:
    commands:
      - echo "Starting SAM packaging `date` in `pwd`"
      - sam --version
      - sam build
      - sam local invoke
  post_build:
    commands:
      # Use Post Build for notifications, git tags and any further customization after build
      # - echo "[Post-Build phase]"
      - echo "SAM packaging completed on `date`"

